name: Snyk Vulnerability Scanner

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - master

jobs:
  dependency_scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g snyk
    - run: git config --list
    - run: echo $${{ github.ref }}
    - run: snyk auth ${{ secrets.SNYK_API_TOKEN }}
    - if: ${{ github.event_name == 'push' && github.ref == '$refs/heads/master' }}
      run: |
        [ -z "$SNYK_PROJECT_NAME" ] && SNYK_PROJECT_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        snyk monitor --org=$SNYK_ORG_ID \
        --project-name=$SNYK_PROJECT_NAME
      env:
        SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
        SNYK_PROJECT_NAME: ${{ secrets.SNYK_PROJECT_NAME }}
    - run: |
        snyk test --json-file-output=/tmp/snyk-test.json \
        -p --severity-threshold=high
    - name: Snyk test report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: snyk-test-report
        path: /tmp/snyk-test.json


